# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

target 'BeeStrong' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  

  # Pods for BeeStrong

  pod 'KDCalendar', '~> 1.8.4'
  pod 'GoogleAPIClientForREST/Calendar'
  pod 'GoogleSignIn' 

end
